### ISSUE TITLE
Valiant has a blur cone with AstronomersVisualPack's TUFX profile

### ISSUE THREAD

**Issue by CPCTC** [KnightofStJohn/StockWaterfallEffects#17]
See [AVP #26](https://github.com/themaster402/AstronomersVisualPack/issues/26).

If you need any more information/logs, let me know!

**Comment by CPCTC** [comment]
I'm increasingly uncertain this is an SVE bug, so feel free to close this if you like.

**Comment by LGhassen** [comment]
Fyi this is fixed in Scatterer 0.0835. Just update it.

If you want to know the technical reason, waterfall seems to output alpha values superior to 1 (values like 100) which were throwing off the Scatterer TAA neighborhood clipping. If you don't have hdr enabled all is well. If you have enabled hdr from tufx you get the issue.

**Comment by CPCTC** [comment]
Awesome, thank you so much.
